# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_board',
            field=models.CharField(default='', max_length=960),
        ),
    ]
