# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0002_user_use_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_board',
            new_name='user_board',
        ),
    ]
