# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0003_auto_20170211_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
