# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0004_auto_20170211_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
