# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0005_user_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='win',
        ),
    ]
