# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0006_remove_user_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='black_king',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='black_left_rook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='black_right_rook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='white_king',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='white_left_rook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='white_right_rook',
            field=models.BooleanField(default=True),
        ),
    ]
